<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\AutomatedTask;
use App\Models\Task;
use App\Models\Client;
use App\Models\Notification;
use Illuminate\Support\Facades\Log;

class RunScheduledTasks extends Command
{
    protected $signature = 'app:run-scheduled-tasks';
    protected $description = 'Execute scheduled task rules that are due today';

    public function handle()
    {
        $this->info('Checking scheduled tasks...');

        $rules = AutomatedTask::where('is_active', true)
            ->whereNotNull('service_id')
            ->whereNotNull('assign_to_user')
            ->get();

        $totalCreated = 0;

        $currentHour = now()->format('H:00');

        foreach ($rules as $rule) {
            if (!$rule->shouldRunToday()) {
                continue;
            }

            if ($rule->hasRunToday()) {
                $this->info("  Skipping \"{$rule->name}\" - already ran today");
                continue;
            }

            // Check if current hour matches the rule's run time
            $ruleTime = $rule->run_at_time ?? '08:00';
            if ($currentHour !== substr($ruleTime, 0, 5)) {
                continue;
            }

            $count = $this->executeRule($rule);
            $totalCreated += $count;
            $this->info("  Ran \"{$rule->name}\": created $count tasks");
        }

        $this->info("Done. Total tasks created: $totalCreated");
    }

    public function executeRule(AutomatedTask $rule)
    {
        // Find all clients with this service active
        $clients = Client::whereHas('activeServices', function ($q) use ($rule) {
            $q->where('services.id', $rule->service_id);
        })->orderBy('name')->get();

        $count = 0;
        $service = $rule->service;

        foreach ($clients as $client) {
            // Build task title from template
            $title = str_replace(
                ['{client_name}', '{client}', '{service_name}', '{service}'],
                [$client->name, $client->name, $service->display_name, $service->display_name],
                $rule->task_template
            );

            // Check if similar task already exists and is not completed
            $existing = Task::where('title', $title)
                ->where('client_id', $client->id)
                ->whereIn('status', ['pending', 'in_progress'])
                ->first();

            if ($existing) {
                continue; // Don't create duplicate
            }

            // Calculate due date
            $dueDate = null;
            if ($rule->due_in_days) {
                $dueDate = now()->addDays($rule->due_in_days)->toDateString();
            } elseif ($service->default_deadline_days) {
                $dueDate = now()->addDays($service->default_deadline_days)->toDateString();
            }

            // Create task
            $task = Task::create([
                'title' => $title,
                'description' => "Auto-generated by scheduled rule: {$rule->name}\nService: {$service->display_name}",
                'client_id' => $client->id,
                'created_by' => $rule->assign_to_user,
                'status' => 'pending',
                'due_date' => $dueDate,
                'priority' => $rule->priority,
            ]);

            // Assign to user
            $task->assignedUsers()->attach($rule->assign_to_user);

            // Send notification
            Notification::create([
                'user_id' => $rule->assign_to_user,
                'client_id' => $client->id,
                'title' => 'Scheduled Task: ' . $service->display_name,
                'message' => $title,
                'type' => 'task',
                'priority' => $rule->priority == 2 ? 'high' : ($rule->priority == 1 ? 'medium' : 'low'),
                'related_task_id' => $task->id,
            ]);

            $count++;
        }

        // Update last run
        $rule->update(['last_run_at' => now()]);

        Log::info("Scheduled task \"{$rule->name}\" executed: $count tasks created");

        return $count;
    }
}
